### ISSUE TITLE
Router won't change the url if root url is not set

### ISSUE THREAD

**Issue by komlev** [jdlehman/jsrouter#6]
WORKS
router.map(match => {
   match('/').to('home');
   match('/login').to('login');
})
router.navigate('/login') //goes to http://localhost:8080/#/login

DOES NOT WORK
router.map(match => {
   match('/login').to('login');
})
router.navigate('/login') //stays on http://localhost:8080/#/

**Comment by jdlehman** [comment]
Yep, that is definitely a bug, I am able to reproduce it locally. It looks like when the root url is not set, it navigates to the route and then leaves it immediately.

I will look into this more tonight.

**Comment by jdlehman** [comment]
This should be fixed in the latest release `0.5.0`.
